import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Footer from "@/app/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,params
}: Readonly<{
  children: React.ReactNode,params:any
}>) {
  console.log('childer000---',params)
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        {children}
        </main>
        {/* {<Footer/>} */}
      </body>
    </html>
  );
}
